### ISSUE TITLE
Reset by the peer

### ISSUE THREAD

**Issue by MrChenhtlss** [sctg-development/sctgdesk-server#5]
Running on my server for a while
I don't know why "Reset by the peer" happens so frequently with almost all remote devices nowadays.
But if I try to establish connection multiple times, I can connect to the device
I tried turning off the server's firewall but it's still there

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/242f0a68-8f8a-44e8-bb2d-426e429dca0a">

![469DD8A0-DE38-4D7A-8D95-271E1EFD2F24](https://github.com/user-attachments/assets/fb402a5d-050c-4c85-95ba-acbc757f9cb3)

https://github.com/user-attachments/assets/88f3ed1e-793c-4465-8027-f0df70ab5bf2

**Comment by aeltorio** [comment]
Dear @MrChenhtlss,

I have completed a 48-hour test, during which I maintained 4 connections open. These connections were spread across 4 different machines, each on a separate network. Throughout this testing period, I did not encounter any "reset by peer" errors. The version of RustDesk used for this test corresponds to the git commit with the hash [d5dfe5a1eb204dc36be97b4b3a17b0d881aa0a3a](https://github.com/rustdesk/rustdesk/tree/d5dfe5a1eb204dc36be97b4b3a17b0d881aa0a3a).

Best regards.

**Comment by MrChenhtlss** [comment]
> Dear @MrChenhtlss,
> 
> I have completed a 48-hour test, during which I maintained 4 connections open. These connections were spread across 4 different machines, each on a separate network. Throughout this testing period, I did not encounter any "reset by peer" errors. The version of RustDesk used for this test corresponds to the git commit with the hash [d5dfe5a1eb204dc36be97b4b3a17b0d881aa0a3a](https://github.com/rustdesk/rustdesk/tree/d5dfe5a1eb204dc36be97b4b3a17b0d881aa0a3a).
> 
> Best regards.

I have ruled out the problem for a long time because the system mirroring template of my server provider adjusted the UDP recv buffer size.
Edit file`/etc/sysctl.conf` Find keywords `net.core.rmem_max=`Delete or annotate it and restart the server
This issue is related to the server provider's system image
Please mark it as answer and close this issues

**Comment by aeltorio** [comment]
I've  updated the [FAQ wiki page](https://github.com/sctg-development/sctgdesk-server/wiki/Troubleshooting)
