### ISSUE TITLE
How to delete the admin user.

### ISSUE THREAD

**Issue by ceozero** [sctg-development/sctgdesk-server#6]
After I delete it in the database, it still creates an admin user by default. This is very insecure.

**Comment by eltorio** [comment]
Could you explain your whole process?

**Comment by ceozero** [comment]
I used the database editor directly to open the db_v2.sqlite3 and deleted the admin's user.

**Comment by aeltorio** [comment]
Hi @ceozero,

Thank you for raising this issue. The behavior you mentioned is the result of the initialization sequence:
```sql
INSERT OR IGNORE INTO user VALUES(X'018f2556230179eb91a2cffe5ced4236','admin','admin@example.org',NULL,'$2b$12$.SfrHeV5frv0FQTM8X33OerLMu1YthqJdMP1oqpFUGh7dfgr41iGG','',1,X'018f255622fb73ee9afdbbcdc0cc387b','2024-04-28 15:32:33',X'018f255622f77778a006702ca5c23714',1,'{"email_alarm_notification":true}',NULL,NULL);
```
This behavior is expected and not a security vulnerability. The default admin credentials can be changed, and the admin username can be manually updated if necessary. However, the ID X'018f2556230179eb91a2cffe5ced4236' must remain unchanged.

Please let me know if you have any further concerns.

Best regards,
Ronan
